print ('Hello, wecome back from vacation. please answer a few questions about your time off school.' )
name = input (' what is your name? ')
print (name)
vacation_spot = input ('where did you go?')
print (vacation_spot)
favorite_food = input ('what was the best food you ate while there?')
print (favorite_food)
favorite_part = input ('what was the best part about being there?')
print (favorite_part)
print (f'Everyone, meet {name}! {name} time off was spent at {vacation_spot}. {name} favorite food there was {favorite_food}. {name} most memorable part was {favorite_part}. ')
